### ISSUE TITLE
Lifting up `displayName` example?

### ISSUE THREAD

**Issue by jamespantalones** [JoviDeCroock/prefresh#103]
Hi there, 

having problems getting this to work with `preact/compat` version using `React.memo` HOC. 

If i have a component like: 

```tsx

export const Component = React.memo(function Foo(){
  return <h1>Yo</h1>;
});

```

I receive an error like `cannot read displayName of undefined`.

This also happens with `React.forwardRef`

Setting `Componet.displayName = 'Foo';` does not solve it.

Any ideas?

Many thanks

**Comment by JoviDeCroock** [comment]
I'll need a bit more information on what integration, ... You are using

**Comment by jamespantalones** [comment]
thanks for getting back so fast. was using the webpack integration with `react-refresh/babel` plugin

However, I was able to solve by simply lifting out the inner function into same scope as HOC like so:

```js

function Foo(){
   return <h1>yo</h1>;
}

export const Component = React.memo(Foo);

```

**Comment by JoviDeCroock** [comment]
I'm going to see if I can solve this/ warn for it Thank you so much for bringing this to my attention!

**Comment by JoviDeCroock** [comment]
This will be fixed in the next release!
