### ISSUE TITLE
Vite 1.0

### ISSUE THREAD

**Issue by yyx990803** [JoviDeCroock/prefresh#110]
I just released [Vite 1.0.0-beta.1](https://github.com/vitejs/vite/blob/master/CHANGELOG.md#100-beta1-2020-06-19) which includes a number of breaking changes. Specifically, the transform API has changed and now also supports returning source map via `return { code, map }`.

Let me know when you have a compatible release and I will update the template in `create-vite-app`. Thanks!

**Comment by JoviDeCroock** [comment]
This has been fixed by https://github.com/JoviDeCroock/prefresh/pull/111 and published under v0.10.0 and is upstreamed for create vite app in https://github.com/vitejs/create-vite-app/pull/33
