### ISSUE TITLE
what's the difference between @prefresh/vite and vite's native hmr?

### ISSUE THREAD

**Issue by beetaa** [JoviDeCroock/prefresh#113]
I have a simple question: when vite comes with [hot module reload](https://github.com/vitejs/vite#hot-module-replacement) itself, what's the differences between them? thanks for anybody's help. @yyx990803

**Comment by JoviDeCroock** [comment]
Prefresh is meant for Preact, so it’s an implementation using vite’s hmr rather than a replacement.

**Comment by beetaa** [comment]
@JoviDeCroock thanks your quick reply.
