### ISSUE TITLE
@prefresh/nollup v1.0.0 missing from npm

### ISSUE THREAD

**Issue by piotr-cz** [JoviDeCroock/prefresh#148]
Latest tagged version of `@prefresh/nollup` in npm [is 0.7.0](https://www.npmjs.com/package/@prefresh/nollup), but in [repo it's 1.0.0](https://github.com/JoviDeCroock/prefresh/blob/c82c4f10e81177d4120b30a06b8bf600400e6093/packages/nollup/package.json)

**Comment by JoviDeCroock** [comment]
Yes it isn't published yet, it's ready for publish

**Comment by piotr-cz** [comment]
OK, no pressure.
I thought you forgot to publish release

**Comment by JoviDeCroock** [comment]
Released it, thanks for the nudge! 😄
