### ISSUE TITLE
Not working with snowpack it does a full page refresh

### ISSUE THREAD

**Issue by cj** [JoviDeCroock/prefresh#160]
To recreate do:

```
npx create-snowpack-app test-preact --template @snowpack/app-template-preact --use-yarn
cd test-preact
yarn start
```

Then go to `src/App.jsx` and change `reload.` to `reload!` and you will see it do a full page reload.

**Comment by JoviDeCroock** [comment]
Hey @cj

Thank you for reporting this issue, I found the fix and I'm releasing the 1.1.1 plugin in a bit!
