### ISSUE TITLE
@prefresh/snowpack missing @prefresh/vite dependency

### ISSUE THREAD

**Issue by drwpow** [JoviDeCroock/prefresh#176]
In `@prefresh/snowpack/dist/index.js`, the following code is found:

```
'import' { flushUpdates } from '@prefresh/vite/utils';
```

However, `@prefresh/vite` is missing from both `dependencies` and `peerDependencies`. This throws a “module not found” error in Snowpack. Is there a way that can be added to `dependencies`, so that it’s automatically installed?

**Comment by JoviDeCroock** [comment]
Oh, seems like my `build` command didn't run properly last time I published and it has the old code. My bad sorry republishing

**Comment by JoviDeCroock** [comment]
Very sorry about that, published 1.1.4 which addresses this issue https://www.runpkg.com/?@prefresh/snowpack@1.1.4/dist/index.mjs

**Comment by drwpow** [comment]
Awesome, thank you! And no worries—just happened to notice it today.

Thanks for the quick response!
