### ISSUE TITLE
Parcel integration

### ISSUE THREAD

**Issue by JoviDeCroock** [JoviDeCroock/prefresh#18]
Integrate with Parcel 2 (maybe 1 as well if possible)

**Comment by mischnic** [comment]
I would love to eventually integrate this into Parcel 2. Since React Fast Refresh is enabled by default as well (and the plugins needed for both are essentially the same), it would make sense to just select between Preact and React in the existing plugins and not create another set (because 3 plugins are needed).

A test from the last week (everything seems to work): https://github.com/JoviDeCroock/prefresh/compare/master...mischnic:parcel

**Comment by mischnic** [comment]
1. I guess it would make sense to keep the plugins in userland (for now) to make development easier.

2. I reused Webpack's template except for three minor changes, maybe more can be shared?
	- `module.__proto__.exports` isn't set by Parcel
	- `require.cache` isn't set (and it seems to work without that line)
	-  The user might define a variable that is later declared by the prefresh wrapper as well, causing a SyntaxError because a try statement doesn't create a scope (maybe Webpack is susceptible to this as well):
```js
import { h } from 'preact';
import { useState } from 'preact/hooks';

export function App() {
  const [v] = useState(Math.random());
  return (
    <div>
      App {v}
    </div>
  );
}

var shouldBind = true; // <-- var isn't scoped to the (inserted) surrounding try body
```

**Comment by JoviDeCroock** [comment]
@mischnic Hmm I think this is a reasonable shortcoming for now, Let's see if we can do something about it but normally the `module.hot` will pick this up when it comes to webpack.

I don't mind to let the `parcel` plugins live in user land, up to you all since I'm not really a parcel-plugin expert. I'm doing my best to help out everywhere I can

**Comment by JoviDeCroock** [comment]
@mischnic I'll try and get rid of all variable declarations and give the ones that remain a more obscure name. Thanks for notifying me about this!

**Comment by mischnic** [comment]
So the only thing that isn't working as is recovering from an error in the render function:

```diff
--- prefresh/packages/parcel-example/src/App.js
+++ prefresh/packages/parcel-example/src/App2.js
@@ -4,11 +4,13 @@ import { useState } from 'preact/hooks';
 export function App() {
   const [v] = useState(Math.random());
   const [w] = useState(Math.random());

+  throw new Error();
+
   return (
     <div>
       Test <br />
       {v} <br /> {w}
     </div>
   );
 }
```

I would have tried this with the Webpack plugin but I couldn't find a full example project.
Is this supposed to work? (At the moment, no updates once applied after the error is removed again)

**Comment by JoviDeCroock** [comment]
@mischnic Yes this is a known issue for nollup and webpack. I'm trying to figure out how to solve this, should make an issue for it. I might have time tomorrow

**Comment by JoviDeCroock** [comment]
An update on this, I've identified this as an issue on Preact where the `rerenderCount` isn't correctly reset [here](https://github.com/preactjs/preact/blob/master/src/component.js#L211) when a component throws and no error/suspense boundaries are hit. Talking to the team as we speak.

**Comment by JoviDeCroock** [comment]
This will be solved like [this](https://github.com/JoviDeCroock/prefresh/pull/57/files) and will be supported in the next Preact release, the next release isn't a hard requirement but gracious handling will only be supported from then on.

**Comment by JoviDeCroock** [comment]
@mischnic is this blocked somehow? Is there a way I can help out? Trying to reduce the open issues atm 😄

**Comment by mischnic** [comment]
No particular problem. It's just that I my branch wasn't rebased in a while.

Maybe this could also be added to Parcel by default if everything works

**Comment by jakehamilton** [comment]
Hi there folks 👋
Is this issue still being worked on?
