### ISSUE TITLE
Update snowpack plugin to integrate babel

### ISSUE THREAD

**Issue by FredKSchott** [JoviDeCroock/prefresh#198]
We just updated our Snowpack `react-refresh` plugin to handle the Babel transformation internally, so that users didn't need to run their entire build through babel (and could use our much faster internal esbuild engine).

See code change here: https://github.com/pikapkg/snowpack/commit/d69dbfe65960c3c14e3319cf664d2bef7cd8b6fe#diff-7d556bd4dfdd12da42c4d2584d5ea928

Are you able to make the same change to prefresh/snowpack? I assume most of the code in the diff linked above could be directly copied into your plugin (plus, the readme will get much simpler).

**Comment by FredKSchott** [comment]
Just saw that you're already doing that in the Vite plugin, so should be relatively straightforward!

**Comment by JoviDeCroock** [comment]
Hey,

Thanks for notifying me, made a PR: https://github.com/JoviDeCroock/prefresh/pull/199
