### ISSUE TITLE
Snowpack integration readme advocating installing prefresh as a production dependency

### ISSUE THREAD

**Issue by Siilwyn** [JoviDeCroock/prefresh#213]
:wave: wondering why the readme shows the install command with the `-s` flag, which as far as I know is the shorthand of `--save-prod`.
Since I'm using snowpack with this as a plugin I would expect the `--save-dev` flag, is the expected usecase for development tooling?

**Comment by JoviDeCroock** [comment]
Sounds right, feel free to PR was an oversight.
