### ISSUE TITLE
Custom hook refresh leaves stale ref

### ISSUE THREAD

**Issue by JoviDeCroock** [JoviDeCroock/prefresh#22]
When we update a `custom hook` we leave a stale reference in the `Functional Components` using this hook. We need to find a way to ensure we're calling `forceUpdate()` with the updated hook on these vnodes.

Let's say we update `useCustomState.js` to return a different callback, this is implemented in our `App.js` file. module.hot will trigger for `useCustomState` and we'll know this is connected to the App type and it's vnode, however if we'd just force the update of this vnode we'd be executing a function with the stale version of `useCustomState`. We'd have to force webpack to reevaluate this constructor (or need a way to get the new version of this constructor).

Concrete example:

```
export const useCounter = () => {
  const [count, setCount] = useState(0):
  return [count, () => { setCount(count + 1) }];
}
```

```
const Counter = () => {
  const [count, increment] = useCounter();
  return (
    <div>
      <p>Count: {count}</p>
      <button onClick={increment}>Increment</button>
    </div>
  );
}
```

Changing the second argument to increment by 2 will successfully get accepted but the event-handler will still only increment by 1.

**Comment by developit** [comment]
for my own sake: https://astexplorer.net/#/gist/f792ef6b7fbfdf33f9124dd5d4fbb6fc/598d72bef20bd8f7413a2fad3ad82f1f102cad59
