### ISSUE TITLE
Unsound peerDeps access error at @prefresh/next on Yarn 2

### ISSUE THREAD

**Issue by BasixKOR** [JoviDeCroock/prefresh#221]
```
Error: @prefresh/webpack tried to access webpack (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: webpack (via "webpack")
Required by: @prefresh/webpack@virtual:7d758bd9f857a39516ef00deff4e009215496d45f0664e44fcd5921e3bbf31b449603b3a1630983c6ac969fafd484ba35897d2b0ffae9fd5dafbaa62ea02fd8f#npm:2.2.0 (via D:\Projects\resume\.yarn\$$virtual\@prefresh-webpack-virtual-f37962971e\0\cache\@prefresh-webpack-npm-2.2.0-41dd1f9fac-3d3a71ba83.zip\node_modules\@prefresh\webpack\src\)
Ancestor breaking the chain: @prefresh/next@virtual:e423ff8dd12617a734705d7c2831166dc44260c750800a9c143a7ded982feaa19601bfed60c052668ee6c393a00f11719559cd5a2d4b4f5cd1a89f6abaf2b561#npm:1.4.0
```

I just encountered this error while using `next-plugin-preact`. I think this can be reproduced by using `@prefresh/next` and `next` with Yarn PnP, but I haven't tested it yet.

# Workarounds
You can use packageExtensions:

```yml
packageExtensions:
  '@prefresh/next@*':
    peerDependencies:
      webpack: '*'
```

**Comment by JoviDeCroock** [comment]
Yes, this is an issue with strict-package managers in general... I personally avoid strict package managers for that reason, this kind off requires webpack to be a peerDep of next-plugin-preact and `@prefresh/next` but it's quite cumbersome to do this stuff.

**Comment by BasixKOR** [comment]
It seems like adding webpack as peerDeps in `@prefresh/next` resolves this issue. Would you merge a PR adding webpack as peerDeps?

**Comment by JoviDeCroock** [comment]
I'd gladly do so!

**Comment by merceyz** [comment]
> Yes, this is an issue with strict-package managers in general

Relying on hoisting to make it availiable is a really bad idea either way, suggest giving these a read
https://dev.to/arcanis/implicit-transitive-peer-dependencies-ed0
https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies
