### ISSUE TITLE
[Webpack] Matcher doesn't ignore code coming from node_modules

### ISSUE THREAD

**Issue by SkaceKamen** [JoviDeCroock/prefresh#225]
The matcher in the plugin doesn't ignore code coming from node_modules, which can result in strange and unexpected behaviour, for example, my compilation crashed with:
```
TypeError: __webpack_require__(...) is not a function
```

Seems like the condition here is flipped:

https://github.com/JoviDeCroock/prefresh/blob/5bbf5b2f9b36e672b79f542e88aa981dc130e066/packages/webpack/src/index.js#L17

Inverting it fixed the issue for me.

**Comment by JoviDeCroock** [comment]
It does https://github.com/JoviDeCroock/prefresh/blob/5bbf5b2f9b36e672b79f542e88aa981dc130e066/packages/webpack/src/utils/constants.js#L8

**Comment by SkaceKamen** [comment]
Yep, I understand that, but the condition is flipped and the `nextMatcherOptions` are used for non-next builds and vice-versa :)

**Comment by JoviDeCroock** [comment]
Yes, I do see that but the initial assessment assumes that we have another issue since the next-options also ignore node_modules so where are we getting this issue from?

**Comment by SkaceKamen** [comment]
You're right, my initial assessment that the condition was the only issue was incorrect.

The regex used for excluding in `nextMatcherOptions` doesn't work in Windows, since `\` is used as path delimiter and the regex only expects `/`. Should've mentioned I'm working on Windows, sorry about that.

Example path that passes the matcher:
```
...ixel\client\node_modules\webpack\buildin\module.js
```

The "non-next" options worked fine since they weren't using path delimiters...

**Comment by JoviDeCroock** [comment]
All right publishing, sorry about that!

**Comment by SkaceKamen** [comment]
Thanks for your work! 👍
