### ISSUE TITLE
Preact + lazy loading error

### ISSUE THREAD

**Issue by olehreznichenko** [JoviDeCroock/prefresh#227]
Hello. When preact trying to render lazy-loaded component `lazy(() => import('Component'))` it is failing with error which you can see in attached screenshots, it goes from `prefresh` which I enabled in `snowpack` config.
Everything works fine if disable `@prefresh/snowpack`

![image](https://user-images.githubusercontent.com/11960153/100876356-f0df0180-34af-11eb-8fac-1da3b775d0fa.png)
![image](https://user-images.githubusercontent.com/11960153/100876453-12d88400-34b0-11eb-8901-06d9b09c13c7.png)

**Comment by JoviDeCroock** [comment]
That would mean that the `options` object is `undefined` which feels to me like a dependency optimization (or double dependency inclusion) within Snowpack. We've seen a similar issue with vite where it optimizes deps in a certain way.

CC @FredKSchott

**Comment by olehreznichenko** [comment]
Doesn't help...
![image](https://user-images.githubusercontent.com/11960153/100882605-0bb57400-34b8-11eb-8342-ee11331b0a52.png)

**Comment by JoviDeCroock** [comment]
I've attempted to reproduce this issue [here](https://github.com/JoviDeCroock/prefresh/commit/7146d41a177f21e0554a1fb2bff74f4c7d279e80) which seems to work correctly.

**Comment by JoviDeCroock** [comment]
Closing for now, feel free to reopen if there's something we can change in prefresh to accomodate this.
