### ISSUE TITLE
Fast refresh breaks when using nextjs withRouter HOC

### ISSUE THREAD

**Issue by sidujjain** [JoviDeCroock/prefresh#229]
It seems that `withRouter` HOC from "next/router" starts `displayName` with a small letter. 

```
if (process.env.NODE_ENV !== 'production') {
    const name =
      ComposedComponent.displayName || ComposedComponent.name || 'Unknown'
    WithRouterWrapper.displayName = `withRouter(${name})`
  }
```

Would it make sense to change the capital letter requirement? 

https://github.com/vercel/next.js/blob/canary/packages/next/client/with-router.tsx

**Comment by JoviDeCroock** [comment]
Isn't this the same requirement as the one for `react-refresh`?

**Comment by sidujjain** [comment]
Fast refresh seems to work well if I use react but breaks after changing to preact. I'm not sure but you can probably use `RefreshRuntime.isLikelyComponentType` to check: 

https://github.com/facebook/react/blob/9aca239f11f31109dc1a229aa1571c2bf02f5524/packages/react-refresh/src/ReactFreshRuntime.js#L671

**Comment by JoviDeCroock** [comment]
It's a function, so if you follow the code the only thing that gets executed is the upper case test 

- test: https://github.com/facebook/react/blob/9aca239f11f31109dc1a229aa1571c2bf02f5524/packages/react-refresh/src/ReactFreshRuntime.js#L695-L696
- withRouter is a func: https://github.com/vercel/next.js/blob/canary/packages/next/client/with-router.tsx#L29

**Comment by sidujjain** [comment]
You are correct. The only difference I can see is that in the case of react-refresh, `name` takes precedence over `displayName`. In the case of `withRouter`, name is returned as ` WithRouterWrapper`, while the display name is `withRouter(...)`

https://github.com/facebook/react/blob/9aca239f11f31109dc1a229aa1571c2bf02f5524/packages/react-refresh/src/ReactFreshRuntime.js#L695

https://github.com/JoviDeCroock/prefresh/blob/main/packages/webpack/src/utils/prefresh.js#L30

**Comment by JoviDeCroock** [comment]
New version has been published, you'll have to upgrade `@prefresh/webpack` to the new patch! Thanks for  the detailed issue

**Comment by sidujjain** [comment]
Thanks for the quick fix! I'll test it out.

**Comment by sidujjain** [comment]
That works now. Though it's now breaking for `react-redux/connect` which gets `u` as the `name` but `Connect(...)` as `displayName`.  `prototype.isReactComponent` check can be added which is true for connect wrapped components. Happy to raise a PR.

**Comment by JoviDeCroock** [comment]
Feel free to raise a PR 👍
