### ISSUE TITLE
Hooks (useState) invalidation

### ISSUE THREAD

**Issue by mischnic** [JoviDeCroock/prefresh#23]
Replacing the declaration `w` with the comment in the next line doesn't reset the state.
```js
export function App() {
  const [v] = useState(Math.random());

  const [w] = useState(Math.random());
  // const [w] = useState(Math.random() + 1);

  return (
    <div>
      App <br />
      {v} <br /> {w}
    </div>
  );
}
```
This might seem fine but if the datatype of the state changes and the value is used accordingly, you might get an invalid UI state.
(React Fast Refresh invalidates `App`'s state in this case and also when renaming the variable name `w` to something else for the same reason.)

**Comment by JoviDeCroock** [comment]
Just tested this locally and it works for me, is it possible you're not adding `react-refresh/babel` to your babel plugins? This was implemented as of `@prefresh/core` version 0.5.0

**Comment by mischnic** [comment]
> is it possible you're not adding react-refresh/babel to your babel plugins

Indeed 😬 👍

**Comment by travomic** [comment]
Does @prefresh/vite v0.10.0 need `react-refresh/babel` installed?  I am getting broken return type behavior on initial render passes for preact/compat aliased hooks.

https://github.com/travomic/battle-orb/pull/24/files#diff-d47481d24720bd5625e4e96253f20f6ad872730b8c8b3871a91c873a836b9acaR12
