### ISSUE TITLE
Incorrect peer dependencies

### ISSUE THREAD

**Issue by phuctm97** [JoviDeCroock/prefresh#246]
Hi @JoviDeCroock, thank you for creating this amazing tool. I'm using it with Snowpack fine without `@prefresh/babel-plugin`, looks like it shouldn't be a peer dependency? Am I correct?

**Comment by JoviDeCroock** [comment]
Correct, it did before but we pulled that into the package itself.

**Comment by phuctm97** [comment]
Thank you, I'll make a PR then.
