### ISSUE TITLE
@prefresh/webpack @prefresh/next __webpack_require__(...) is not a function

### ISSUE THREAD

**Issue by NewNik** [JoviDeCroock/prefresh#257]
@prefresh/webpack version 3.0.0 does not work with @prefresh/next.

![image](https://user-images.githubusercontent.com/29460421/105579069-412e5d80-5d95-11eb-87ba-88d0e19b1c40.png)

Problem in method "matcher" in class "ReloadPlugin".

It looks like the constant "nextMatcherOptions" excludes the modules needed for prefresh to work.

if replace in the file "@prefresh\webpack\src\utils"
`exports.nextMatcherOptions = {`
`   include: /\.([jt]sx?)$/,`
`   exclude: /node_modules\/(?!next[\\/]dist[\\/]next-server[\\/]lib).*/,`
`};`
with
`exports.nextMatcherOptions = {`
`   include: /\.([jt]sx?)$/,`
`   exclude: /node_modules/,`
`};`
everything works fine

**Comment by JoviDeCroock** [comment]
I guess this is only an issue with latest next since they must've changed something that breaks this regex, this regex is intentionally so so that `next/async` and `next/router` would work.

**Comment by tiagooliveira08** [comment]
we still have no solution? 
@JoviDeCroock

**Comment by JoviDeCroock** [comment]
That's kinda rude 😅 there is no outline of what the issue is, can't reproduce it currently

**Comment by NewNik** [comment]
> There is no outline of what the issue is, can't reproduce it currently. #260 runs next-latest and isn't running into this issue, is there some special next dep that you're using in here? @NewNik

Used this example
https://github.com/developit/nextjs-preact-demo

when npm install works correctly
when yarn install gets error __webpack_require __ (...) is not a function

The bottom line is that npm installs packages according to package-lock.json
yarn ignores package-lock.json and installs new versions of packages

package-lock.json
![image](https://user-images.githubusercontent.com/29460421/106181517-bee7d400-61ae-11eb-8037-48e331eb0d0d.png)

yarn.lock after yarn install
![image](https://user-images.githubusercontent.com/29460421/106181578-d6bf5800-61ae-11eb-9db2-e8007b93f654.png)

Comparing the versions of the prefresh packages, I came to the conclusion that the problem is in the @prefresh/webpack@^3.0.0

This problem was described above

**Comment by JoviDeCroock** [comment]
Have you tried using the official next plugin? https://github.com/preactjs/next-plugin-preact/tree/master/packages/next-plugin-preact

**Comment by NewNik** [comment]
Yes, tried building next app with preact using plugin https://github.com/preactjs/next-plugin-preact/tree/master/packages/next-plugin-preact

The error described in the first message occurs

**Comment by JoviDeCroock** [comment]
![image](https://user-images.githubusercontent.com/17125876/106184094-61995600-61a1-11eb-8cf7-9c1c6c406c5c.png)

Just ran yarn when using latest and it works for me, could you describe or provide a reproduction repository?

**Comment by NewNik** [comment]
Here is a link to an example with an error.
https://github.com/NewNik/preact-plugin-test
The app starts and builds, but yarn dev renders a blank page (body {display: none;}). In the browser console you can see the error __webpack_require __ (...) is not a function

**Comment by JoviDeCroock** [comment]
Will try this out later today https://github.com/JoviDeCroock/prefresh/pull/262
