### ISSUE TITLE
Prefresh mangles workers in Vite

### ISSUE THREAD

**Issue by NotWoods** [JoviDeCroock/prefresh#266]
When I use the `@prefresh/vite` plugin, my workers fail to load because they expect to extend `HTMLElement`. This seems to be because [this line in `vite/client`](https://github.com/vitejs/vite/blob/main/packages/vite/src/client/overlay.ts#L116) is loaded by the worker. The worker script doesn't reference the client at all, this seems to be injected by the plugin.

**Comment by JoviDeCroock** [comment]
In what way does it mangle? Does Babel inject code? Could you show where it goed wrong?

**Comment by JoviDeCroock** [comment]
We don't inject the `vite/client` afaik... cc @yyx990803 do you have an idea?

**Comment by NotWoods** [comment]
Seems to be related to importing other modules? Here's a minimal reproduction:

https://github.com/NotWoods/prefresh-vite-workers-bug

**Comment by NotWoods** [comment]
Seems like something else is causing the issue for me. I'm trying to create a minimal reproduction but having trouble recreating the bug.

**Comment by NotWoods** [comment]
Here's a minimal reproduction: https://github.com/NotWoods/prefresh-vite-workers-bug

I think the actually issue is that every `class` causes the hot reload script to be injected, even within a worker.

**Comment by JoviDeCroock** [comment]
The hot-reload script specific to prefresh or the one of vite itself? This repo checks whether or not it has JSX/hooks by doing https://github.com/JoviDeCroock/prefresh/blob/main/packages/vite/src/index.js#L37-L39

**Comment by NotWoods** [comment]
Lowercase `class test` does work. If the `@prefresh/vite` plugin is not used, the worker doesn't have any issues.

**Comment by JoviDeCroock** [comment]
We might want to add an exclusion for *.worker.js

**Comment by NotWoods** [comment]
Could the class check be altered so that the class needs to extend `Component` or so that JSX needs to be present in the file?

**Comment by JoviDeCroock** [comment]
Stops working for derivative components where they extend a class that is already extends a component... :/

**Comment by JoviDeCroock** [comment]
I think I got a fix, testing it now

**Comment by NotWoods** [comment]
Unfortunately this doesn't cover my case fully because I'm importing a class from my worker. I appreciate the work covering most cases, seems like this might need a way to check the script context from Vite.
