### ISSUE TITLE
styles in separate files do not update - (Styled components)

### ISSUE THREAD

**Issue by tiagooliveira08** [JoviDeCroock/prefresh#275]
In my project when using prefresh and styles in separate files there is no update.
How to test: run the project, go to the styles.js file, update the style.
The expected behavior is to update the style, but no changes are reflected.

[Repo](https://github.com/tiagooliveira08/prefresh-styled)

**Comment by JoviDeCroock** [comment]
Isn't this the case with React as well, the `pages` directory isn't meant to be used like that

**Comment by tiagooliveira08** [comment]
this was one of the alternatives to separate components / containers, but putting the problem in the default mode still persists.

**Comment by tiagooliveira08** [comment]
I updated the repo to the more conventional mode

**Comment by JoviDeCroock** [comment]
Just as a general note since I haven't had the chance to look at it yet, is this issue present with React as well since this could be related to how bubbling works in next-hmr.

**Comment by tiagooliveira08** [comment]
good morning jovi, do we have any updates?
I did a test and the react works normally, so as not to hinder the progress of the project and the team I am thinking of returning to react.

**Comment by JoviDeCroock** [comment]
I've been diving deeper into this and seems like react-refresh is being injected alongside Prefresh

**Comment by tiagooliveira08** [comment]
right, thank you.
Just by having feedback I can be more relaxed.

**Comment by JoviDeCroock** [comment]
As an update, I haven't forgotten about you, the issue might reside in `next-plugin-preact` or an outdated dep, I've been trying to reproduce it in a test as I'm seeing the issue very present in your example.

It seems like something is preventing the component from being registered within Babel, however when I try this out in a sandbox https://astexplorer.net/#/gist/b4f4c6b8fe115ed02b4e37dc812b352e/90b17afcb13922783465dc6da2d3bbe685bfd5dc it does register both correctly

The testing PR: https://github.com/JoviDeCroock/prefresh/pull/290 this is using webpack 4 just like your setup.

**Comment by JoviDeCroock** [comment]
Update, it seems to work correctly with webpack 4 but not with webpack 5.

**Comment by tbgse** [comment]
Hey @JoviDeCroock jumping onto this issue since this is exactly the same problem we are observing as well. When you posted your last update where you made things work with webpack 4, what exactly did you change to resolve the problem? Did it end up being a problem with `next-plugin-preact` or prefresh?

**Comment by JoviDeCroock** [comment]
Nothing it seemed to just work in https://github.com/JoviDeCroock/prefresh/tree/main/test/fixture/next/src the test runs on `next-webpack4` https://github.com/JoviDeCroock/prefresh/runs/2212010369#step:6:1612 https://github.com/JoviDeCroock/prefresh/blob/main/test/index.test.js#L299

Odd that it doesn't work, let me see if I can find another bug in there

**Comment by tbgse** [comment]
@JoviDeCroock i just created a repo for reproduction as well: https://github.com/tbgse/prefresh-styled-components

One styled component updates without issues when in the same file. But the imported styled components will not update until hard refresh. Would be curious to know if this problem presents for you as well when running this example locally.

**Comment by JoviDeCroock** [comment]
@tbgse I think I found a fix with https://github.com/JoviDeCroock/prefresh/pull/312

**Comment by tbgse** [comment]
@JoviDeCroock just tested - works like a charm! Would it be possible to update the dependency to that latest `@prefresh/webpack` version in the `@prefresh/next` package (and then update the next preact plugin accordingly)?

**Comment by JoviDeCroock** [comment]
@tbgse I'll try to make work of that as soon as possible

**Comment by tbgse** [comment]
Awesome, thanks again for resolving this so quickly - our team is more than excited to have full HMR goodness. ⭐
