### ISSUE TITLE
Using @prefresh/next to develop in IE11

### ISSUE THREAD

**Issue by nickrttn** [JoviDeCroock/prefresh#277]
Hi there,

We're currently working on a project where we need to support IE11. We're working with Next.js using `next-plugin-preact`, which uses `@prefresh/next` for HMR. When trying to develop in IE11, the development build breaks on a script `webpack.js`. It seems to break on this piece of code, defined in `@prefresh/webpack/src/utils/Runtime.js`.

```js
const beforeModule = `
self.$RefreshSig$ = () => {
  let status = 'begin';
  let savedType;
  return (type, key, forceReset, getCustomHooks) => {
    if (!savedType) savedType = type;
    status = self.${NAMESPACE}.sign(type || savedType, key, forceReset, getCustomHooks, status);
    return type;
  };
};
`;
```

I don't thoroughly understand how this works, but it seems that this is injected as a string and eval'ed or something?
I was wondering if you had some advice on how to get this to transpile for IE11? I've tried to use `next-transpile-modules` on the `@prefresh` packages, but that didn't get it to work.

Getting this to work would really help us work on bugs in IE11 with a smaller feedback loop (as opposed to running a build for every change).

If you want to incorporate this into `prefresh` and can point me in the right direction, I'd love to contribute with a PR.

**Comment by JoviDeCroock** [comment]
I guess we'd need to have to write this to be conforming to old syntax, this won't be picked up by transpilation as it's a loader-injected bit.
