### ISSUE TITLE
Add overlay methods like react-refresh-webpack-plugin

### ISSUE THREAD

**Issue by wardpeet** [JoviDeCroock/prefresh#282]
The "official" react-refresh webpack plugin supports apis to handleErrors during fast refresh.
See https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/docs/API.md#module

It would be great if this option was available in the webpack plugin as well. Gatsby uses this to show error overlays. If someone installs gatsby-plugin-preact, fast refresh works great but they have to look in their terminal or devtools to see their errors.

Repro:
```
npx gatsby new preact-error-overlay https://github.com/gatsbyjs/gatsby-starter-default
yarn add gatsby-plugin-preact

// add gatsby-plugin-preact to your gatsby-config.
// make an error in your code
```

APIs fast-refresh supports:
- handleRuntimeError
- clearRuntimeErrors
- showCompileError
- clearCompileErrors

If you're open for contributors, let me know. I'm happy to create a PR for this

**Comment by JoviDeCroock** [comment]
Open to contributions, if you don't get the time I might look at it later this or next week 👍
