### ISSUE TITLE
No "exports" main defined

### ISSUE THREAD

**Issue by Twiggeh** [JoviDeCroock/prefresh#284]
When trying to `import PreactRefreshPlugin from "@prefresh/webpack"` ([from here](https://github.com/JoviDeCroock/prefresh/tree/main/packages/webpack)) I get the following error:

 `No "exports" main defined in /mnt/Storage/projects/Webdev/Work/lttcodetest/client/node_modules/@prefresh/webpack/package.json` 

Didn't know that webpack supports es6 modules now ?

**Comment by JoviDeCroock** [comment]
hmm, I can test again but it does seem to work for me, do you have a reproduction and what version of Node/Webpack

**Comment by Twiggeh** [comment]
Changed everything back to the require syntax, so this is not that big of a deal :D. Will add a minimal example soon.

Also is prefresh like reacts hmr where it keeps the state of the components, or does it "just" rerender the page if any module updated :D ?

Node v15.8.0 
"webpack": "^5.24.4"
"webpack-cli": "^4.5.0"
"webpack-dev-server": "^3.11.2"

**Comment by JoviDeCroock** [comment]
Prefresh is exactly like fast-refresh, this requires you to use the Babel-plugin as well as the Webpack plugin.

If you want to read more about how it actually works: https://dev.to/jovidecroock/prefresh-fast-refresh-for-preact-26kg

**Comment by Twiggeh** [comment]
Reproducable:

To run:
0. `git clone https://github.com/Twiggeh/emotion-no-prod-styles/tree/minHotModuleReplacement` 
1. `cd emotion-no-prod-styles/client && yarn install`
2. (Auto transformed to ES6 Module) `yarn webpack serve --config ./config/webpack.dev.mjs --mode development --host 0.0.0.0 --port 5000 --public localhost

**Comment by JoviDeCroock** [comment]
Hmm, I guess doing `type: 'commonjs'` in our package.json might fix that.
