### ISSUE TITLE
Enabling `hot: true` breaks Preact's Context

### ISSUE THREAD

**Issue by Twiggeh** [JoviDeCroock/prefresh#286]
Enabling HMR stops preact from working completely (broken context api) => `Cannot read property 'getChildContext' of undefined`. 

(Not sure if this is an issue arising from using require instead of import, just close it if its cause by it)

Reproduce with :

1. `git clone -b minHotModuleReplacement https://github.com/Twiggeh/emotion-no-prod-styles/`
2. `cd emotion-no-prod-styles/client && yarn install`
3. `yarn webpack serve --config ./config/webpack.dev.js --mode development --host 0.0.0.0 --port 5000 --public localhost`

Switching between `devServer.hot` `true` and `false` breaks and unbreaks the app

**Comment by JoviDeCroock** [comment]
As said in your previous thread, you are not using the babel plugin, consider using the example https://github.com/JoviDeCroock/prefresh/tree/main/test/fixture/webpack (.babelrc)

**Comment by Twiggeh** [comment]
![image](https://user-images.githubusercontent.com/23149166/110820634-9106ac80-828f-11eb-956b-0d62869611e9.png)


I thought I was :/

**Comment by JoviDeCroock** [comment]
I just went on a witch hunt through your repo and fount the culprit:  `import { hot } from 'react-hot-loader/root';`, I've also put `hot: true` in your devServer, don't know if that had impact
