### ISSUE TITLE
@prefresh/vite@2.1.0 does not work correctly

### ISSUE THREAD

**Issue by joehua87** [JoviDeCroock/prefresh#292]
If I remove the following code, it works normally, 😢

```js
    config() {
      return {
        optimizeDeps: {
          exclude: ['@prefresh/vite/runtime', '@prefresh/vite/utils'],
        },
      };
    },
```

**Comment by JoviDeCroock** [comment]
Can you reproduce this somehow, in the tests we don't seem to be having this issue in latest vite.

**Comment by joehua87** [comment]
Sure, in this file: https://github.com/joehua87/vite-mdx/blob/c29a51cc3ea6e344ac955f8fecab89f00eeebcd6/prefresh/index-2.1.0.mjs#L15 (copy from `@prefresh/vite@2.1.0`)

The console shows: `[vite] hot updated: /src/App.tsx` but **don't actually perform the hot reload**

If I remove the config mentioned above, it will

But would you mind explain about the benefits of excluding `['@prefresh/vite/runtime', '@prefresh/vite/utils']`? Thank you.
