### ISSUE TITLE
Snowpack + Lazy do not refresh component

### ISSUE THREAD

**Issue by grenierdev** [JoviDeCroock/prefresh#306]
#### Step to reproduce
1. `npx create-snowpack-app lazy-bug --template @snowpack/app-template-preact-typescript`
2. Create new component beside `App.tsx`
3. Lazy import component `const MyComp = lazy(() => import('./MyComp'));` on line 5
4. Change something in the new component

#### Bug
My App component is not refreshed. The browser seems to load the component fine through `hmr-client.js` (seen in the Network tab of the devtool)

**Comment by grenierdev** [comment]
Found my problem. I was using _unnamed component_ `export default () => {...}`. Didn't read carefully enough the part on [Recognition](https://github.com/JoviDeCroock/prefresh#recognition) in the readme.

**Comment by JoviDeCroock** [comment]
Glad to hear it's working, was going to look into it cause I thought it might've been on my side 🙌 feel free to raise an issue in case you find other lacking parts.
