### ISSUE TITLE
correct way to add a babel plugin (vite)

### ISSUE THREAD

**Issue by martoche** [JoviDeCroock/prefresh#311]
Hi,

I'm trying to figure out what is the best way to add a babel plugin.

It all started when I had the error:

```
unknown: Support for the experimental syntax 'classProperties' isn't currently enabled 
```

which then suggested to add the `@babel/plugin-syntax-class-properties` plugin.

My app was created with the preact template of Vite's create-app. It looks like Vite imports `@preact/preset-vite`, which then imports `@prefresh/vite`. So I made the following change my local version of this file https://github.com/JoviDeCroock/prefresh/blob/main/packages/vite/src/index.js#L107:

```diff
- plugins: [[prefreshBabelPlugin, { skipEnvCheck: true }]],
+ plugins: [[prefreshBabelPlugin, { skipEnvCheck: true }], "@babel/plugin-proposal-class-properties"],
```

This fixes my problem, but obviously it's just a hack, not the ideal solution.

Is there something obvious that I'm missing? If you're OK with letting the user pass plugins options, let me know if I can help with a pull request.

Thanks a lot!

**Comment by JoviDeCroock** [comment]
We can implement a similar way to how vite does this for the `react-refresh` plugin https://github.com/vitejs/vite/blob/main/packages/plugin-react-refresh/index.js#L81

**Comment by martoche** [comment]
Thanks! 💝
