### ISSUE TITLE
"@prefresh/vite" fails when using "jsxFactory" other than "h" from "preact"

### ISSUE THREAD

**Issue by o-alexandrov** [JoviDeCroock/prefresh#321]
## Problem

Emotion users need to be able to use a custom `jsxFactory`, when using one of the core features of emotion [css prop](https://emotion.sh/docs/css-prop).

<details><summary>When making this change (click to view)</summary>

Switching from the suggested:

```
  esbuild: {
    jsxFactory: `h`,
    jsxFragment: `Fragment`,
    jsxInject: `import { h, Fragment } from "preact";`,
  },
```

To:

```
  esbuild: {
    jsxFactory: `jsx`,
    jsxInject: `import { jsx } from "@emotion/react";`,
  },
```

</details>

The `"@prefresh/vite"` fails with the following error message:
- I'm new to vite, so sorry for not being able to provide you w/ a more useful debug msg

```
Cannot read property '__e' of undefined
```

**Comment by JoviDeCroock** [comment]
I guess it's related to optimizeDeps (vite config), you might want to avoid having that active for this one as currently you have some kind of circular import going on. Options being undefined feels like that atleast.

**Comment by o-alexandrov** [comment]
> I guess it's related to optimizeDeps (vite config)

To be transparent, the following is everything I use in the `vite.config.ts`:

<details><summary>Click to view</summary>

```ts
import prefresh from "@prefresh/vite"
import { defineConfig } from "vite"
/**
 * @see https://vitejs.dev/config
 */
export default defineConfig({
  plugins: [
    (prefresh as any)()
  ],
  esbuild: {
    jsxFactory: `jsx`,
    jsxInject: `import { jsx } from "@emotion/react";`,
  },
  resolve: {
    alias: {
      react: `preact/compat`,
      "react-dom/test-utils": `preact/test-utils`,
      "react-dom": `preact/compat`,
    },
  },
})
```

</details>

As I understand, you assume, I am also using [optimizeDeps](https://vitejs.dev/config/#optimizedeps-entries) options. I'm not.
Could you please clarify what would you like me to test to assist you w/ finding the resolution?

**Comment by JoviDeCroock** [comment]
Try https://vitejs.dev/config/#dep-optimization-options:

```
exclude: ['preact/compat', 'preact', '@prefresh/core']
```

**Comment by o-alexandrov** [comment]
@JoviDeCroock thank you for your help so far.
Please be informed, I tried the suggested change, adding the following to the config:

```
  optimizeDeps: {
    exclude: [`preact/compat`, `preact`, `@prefresh/core`],
  },
```

it didn't help, failing w/ a similar message:

```
Cannot read property '__H' of undefined
```

Then, I tried to exclude other two dependencies that are added by `@prefresh`:

```
  optimizeDeps: {
    exclude: [
      `preact/compat`,
      `preact`,
      `@prefresh/core`,
      `@prefresh/vite`,
      `@prefresh/utils`,
    ],
  },
```

But it fails in the same way.

Making sure that there are absolutely no deps related to `react` and `preact` in the `node_modules/.vite/*` also doesn't help:

```
  optimizeDeps: {
    exclude: [
      `react`,
      `preact/compat`,
      `preact`,
      `preact-render-to-string`,
      `@prefresh/core`,
      `@prefresh/vite`,
      `@prefresh/utils`,
    ],
  },
```

**Comment by JoviDeCroock** [comment]
Mind adding `preact/hooks` as well? Gonna check it out in a bit, not at my computer atm

**Comment by o-alexandrov** [comment]
@JoviDeCroock just did, sorry to inform, it's the same error.
Thank you for taking a look. Please let me know, if I could assist in any other way.

**Comment by JoviDeCroock** [comment]
Well my last guess would be to add `@emotion/core`

**Comment by itsMapleLeaf** [comment]
Here to chime in, I _think_ I'm running into this same bug, and it happens specifically when I try to use suspense; it seems to work otherwise.

I tried to make a standalone reproduction, but I could only reproduce it in my project. [Here's the branch, with the code minimized as much as I could.](https://github.com/itsMapleLeaf/anigreen/tree/preact-with-bug/web/src)

It uses pnpm. Running `pnpm i; pnpm run dev` should work, and open the dev server to localhost:3000

Files of relevance:

- https://github.com/itsMapleLeaf/anigreen/blob/82f40b57e9428eda781a899d7904d317673b468b/web/vite.config.ts
- https://github.com/itsMapleLeaf/anigreen/blob/83a94ee3f1b0a89fb26863c34fc37afdd953fc7d/web/src/main.tsx
- https://github.com/itsMapleLeaf/anigreen/blob/83a94ee3f1b0a89fb26863c34fc37afdd953fc7d/web/src/app/WatchingPage.tsx

Findings:
- Works without suspense usage
- Works when `WatchingPage` is inlined in `main.tsx` instead of imported
- Works when removing  `prefresh()` preset from the config
- Changing the esbuild jsx config has no effect

**Comment by JoviDeCroock** [comment]
@itsMapleLeaf that one is def the optimizeDeps issue, it's not inherent to Prefresh. The issue is that vite will optimize preact in preact/compat which leaves prefresh/core (uses preact) with another preact version or a weird import-state. Can't quite tell which one applies

**Comment by itsMapleLeaf** [comment]
I see, and the "Cannot read __H of undefined" now shows up when I try to add the exclusions, as mentioned earlier:
```js
	optimizeDeps: {
		exclude: [
			"react",
			"react-dom",
			"preact",
			"preact/compat",
			"preact/hooks",
			"@prefresh/core",
			"@prefresh/vite/runtime",
			"@prefresh/vite/utils",
		],
	},
```
So it sounds like an issue with Vite that can/should be fixed on their end?

**Comment by o-alexandrov** [comment]
Btw, as crazy as it sounds, the following addition ended up working.
If you add more deps to the exclusion, vite/esbuild stops working properly throwing different errors related to the exports of the pkgs.

```
  optimizeDeps: {
    exclude: [
      `@prefresh/vite/runtime`,
      `@prefresh/vite/utils`,
    ],
  },
```

I'll be closing it, as I don't have any issues w/ the above.
