### ISSUE TITLE
Gatsby doesn't refresh with this plugin. What should be added to the client?

### ISSUE THREAD

**Issue by adamgen** [JoviDeCroock/prefresh#324]
On the [preact-gatsby-plugin](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-preact) this is added to the backend, but nothing is manually added to the front. Any changes we should make there?

```
const PreactRefreshPlugin = require(`@prefresh/webpack`)
// ...
const webpackPlugins = []
  if (stage === `develop`) {
    webpackPlugins.push(new PreactRefreshPlugin())

    // remove React refresh plugin, we want to add preact refresh instead.
    const webpackConfig = getConfig()
    webpackConfig.plugins = webpackConfig.plugins.filter(
      plugin => plugin.constructor.name !== `ReactRefreshPlugin`
    )
    actions.replaceWebpackConfig(webpackConfig)
  }
// ....

  actions.setWebpackConfig({
    plugins: webpackPlugins,
  })
```

**Comment by JoviDeCroock** [comment]
As long as Gatsby uses the HMR-connection of Webpack stuff should be automatic. All this plugin does is add the code required for HMR to work. All the other stuff required are just the messages that `webpack-dev-server` or `webpack.hotModuleReplacementPlugin` puts on the message channel.
