### ISSUE TITLE
Doesn't work with preact-cli when port is randomly assigned

### ISSUE THREAD

**Issue by JohannesKlauss** [JoviDeCroock/prefresh#332]
If my local 8080 port is already used and I start a preact dev server via `preact watch --refresh` an random open port gets assigned. When that is the case the fast refresh doesn't work.

**Comment by JoviDeCroock** [comment]
This implementation does not depend on any port-logic, that would mean that the signalling server within preact-cli gets assigned to the wrong port.

**Comment by JoviDeCroock** [comment]
Closed due to inactivity, if I can do anything to help you out on the Prefresh side feel free to ping me.
