### ISSUE TITLE
Would this work with preact/compat too?

### ISSUE THREAD

**Issue by lakshyaranganath** [JoviDeCroock/prefresh#60]
Hey team, first off, wonderful job on what you all have done so far 💯 

Just wanted to understand if this will support reloading in config with `preact/compat` aliases as well? (particularly in the webpack 4 case).

If yes, how would one set this up to work in that environment.
If no, is it a case of "it's out of scope" or "support will be added later".

Thanks in advance :)

**Comment by JoviDeCroock** [comment]
This will just work, if you’re using preact-cli this will be an opt-in option and else just follow the Readme for your bundler.

**Comment by lakshyaranganath** [comment]
Sounds great, thank you! 🔥
