### ISSUE TITLE
Hooks break components when using ts-loader + babel-loader + @prefresh/webpack

### ISSUE THREAD

**Issue by Js-Brecht** [JoviDeCroock/prefresh#70]
There seems to be some issue using hooks in components when using `ts-loader` in combination with `babel-loader` + `@babel/preset-env` and `@prefresh/webpack`.  For some reason, components with hooks become `undefined`.

I have created a reproduction [here](https://github.com/Js-Brecht/preact-prefresh-hooks-issue).  If you run the `start` npm script, you will see the issue I'm talking about in your browser.

If you comment out [these lines](https://github.com/Js-Brecht/preact-prefresh-hooks-issue/blob/master/babel-preset.js#L8-L19) (remove `@babel/preset-env`), the problem goes away.

If you return those lines and comment out [these lines](https://github.com/Js-Brecht/preact-prefresh-hooks-issue/blob/master/webpack.config.js#L78-L81) (remove `ts-loader`), then everything works.  But they can't seem to coexist.

Perhaps I have it misconfigured in some way.  Is there something in `@babel/preset-env` that would cause this?  I would very much prefer to use `ts-loader` together with `babel-loader`, because there are also transformations that I want Typescript to make.  However, in development I am using `@prefresh/webpack`, so it refuses to work correctly.

One thing that is different between my main project repo and this reproduction: in my project repo, the element becomes `<undefined>`, and doesn't throw the error in the browser.  There is a lot more going on there, though, so there's apparently something that is allowing it to pass through as `undefined`.  I just didn't bother taking the time to build it up to that point.  I just wanted to showcase the failure.

**Comment by JoviDeCroock** [comment]
This is an odd one so first thing I noticed is that everything actually works fine when I remove `preact/debug` it seems like a transform is making `<App />` into `<undefined />` for a small time until the import is resolved which seems very odd.

**Comment by Js-Brecht** [comment]
Oh!  Good catch!  I forgot I had set that to CJS while I was testing a TS transformer I was working on.

I also hadn't noticed the `preact/debug` import... this was a quick project I scaffolded with `preact create typescript`; I ripped a lot of it out, but I guess I missed that bit.  Once I remove that `require()`, you can see the actual problem I was encountering: inside of `<App>`, I have a text box that uses `useState` for state management.  It will wind up being mounted to the DOM as `<undefined>`.

But you're absolutely right.  Changing the `module` setting in `tsconfig` fixes the entire issue.  Thanks!
