### ISSUE TITLE
Make `@prefresh/vite` compatible with strict package managers

### ISSUE THREAD

**Issue by yyx990803** [JoviDeCroock/prefresh#75]
Currently `@prefresh/vite` injects code that directly imports from `@prefresh/core` and `@prefresh/utils`, which are not direct dependencies of the project, and cause the resolution to fail when using strict package managers like pnpm or yarn 2.

To make it compatible, we should use paths only under `@prefresh/vite`.

**Comment by lukeed** [comment]
I think the easy workaround (altho it looks silly) is to create a sibling `src/runtime.js` file in the `prefresh/vite` and import that [here](https://github.com/JoviDeCroock/prefresh/blob/c2240803a1631061085046da42c64fdcca78e3b8/packages/vite/src/index.js#L24) instead.

```js
// src/runtime.js
import '@prefresh/core';

// src/utils.js
export { compareSignatures } from '@prefresh/utils';

// src/index.js
shouldBind
  ? `
    import './runtime';
    import { compareSignatures } from './utils';
  `
  : ///

**Comment by yyx990803** [comment]
The injected code should be `import '@prefresh/vite/dist/src/runtime'` because it's resolved as a project source file instead of a file inside `@prefresh/vite`.

**Comment by lukeed** [comment]
Updated & confirms that it works locally

**Comment by JoviDeCroock** [comment]
Hey @yyx990803 

@lukeed implemented this and will be part of the next patch release, hoping to do that tonight. Thank you for bringing this to my attention I was not aware of it at all.
