### ISSUE TITLE
@prefresh/vite not working for non-root component

### ISSUE THREAD

**Issue by dannylindquist** [JoviDeCroock/prefresh#94]
In the default vite template for preact, created with
`npx create-vite-app preact-hmr --template preact`, editing the default app.jsx works as expected and is reflected on the page instantly. Any new component created and used within `app.jsx` doesn't cause anything to change in the page when that new component is changed itself.

Posted in Vite. But thought maybe it might be directly related to this instead.
https://github.com/vitejs/vite/issues/388#issue-637305182

**Comment by JoviDeCroock** [comment]
I just tested it in vite 0.16.2 and it seems to work, I'll explore their changelog to see what changed.

**Comment by dannylindquist** [comment]
Thanks. I can confirm it works in vite 0.16.2 for me as well.

**Comment by JoviDeCroock** [comment]
What version are you using for `@prefresh/vite`?

**Comment by dannylindquist** [comment]
I was using vite 0.20.8 with @prefresh/vite 0.8.3 when I encountered the issue.

**Comment by JoviDeCroock** [comment]
All right, I'll publish 0.9.0 tonight 👍

**Comment by JoviDeCroock** [comment]
0.9.1 has been published and should fix the default exports and normal non-root one! Thanks for reporting this issue, also PR'ed the upgrade to the template.
